/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void *init_proc();
int sub_8048490();
// int printf(const char *format, ...);
// size_t strcspn(const char *s, const char *reject);
// char *fgets(char *s, int n, FILE *stream);
// unsigned int alarm(unsigned int seconds);
// int puts(const char *s);
// int system(const char *command);
// void exit(int status);
// unsigned int strtoul(const char *nptr, char **endptr, int base);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// void *memset(void *s, int c, size_t n);
// int _gmon_start__(void); weak
void _x86_get_pc_thunk_bx();
int deregister_tm_clones();
int register_tm_clones();
int _do_global_dtors_aux();
int frame_dummy();
int bring_students_to_school();
int __cdecl main(int argc, const char **argv, const char **envp);
int student_1();
int student_2();
int student_3();
int student_4();
int student_5();
int principal();
void _libc_csu_init(void); // idb
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (*_frame_dummy_init_array_entry[2])() = { &frame_dummy, &_do_global_dtors_aux }; // weak
int (*_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
int (*dword_804A008)(void) = NULL; // weak
char _bss_start; // weak
_UNKNOWN unk_804A043; // weak
// extern struct _IO_FILE *stdin;
// extern struct _IO_FILE *stdout;
// extern _UNKNOWN __gmon_start__; weak


//----- (08048468) --------------------------------------------------------
void *init_proc()
{
  void *result; // eax

  result = &__gmon_start__;
  if ( &__gmon_start__ )
    result = (void *)_gmon_start__();
  return result;
}
// 8048550: using guessed type int _gmon_start__(void);

//----- (08048490) --------------------------------------------------------
int sub_8048490()
{
  return dword_804A008();
}
// 804A008: using guessed type int (*dword_804A008)(void);

//----- (08048560) --------------------------------------------------------
#error "8048563: positive sp value has been found (funcsize=2)"

//----- (08048590) --------------------------------------------------------
void _x86_get_pc_thunk_bx()
{
  ;
}

//----- (080485A0) --------------------------------------------------------
int deregister_tm_clones()
{
  int result; // eax

  result = &unk_804A043 - (_UNKNOWN *)&_bss_start;
  if ( (unsigned int)(&unk_804A043 - (_UNKNOWN *)&_bss_start) > 6 )
    result = 0;
  return result;
}
// 80485A0: could not find valid save-restore pair for ebp
// 804A040: using guessed type char _bss_start;

//----- (080485D0) --------------------------------------------------------
int register_tm_clones()
{
  return 0;
}
// 80485D0: could not find valid save-restore pair for ebp

//----- (08048610) --------------------------------------------------------
int _do_global_dtors_aux()
{
  int result; // eax

  if ( !_bss_start )
  {
    result = deregister_tm_clones();
    _bss_start = 1;
  }
  return result;
}
// 8048610: could not find valid save-restore pair for ebp
// 804A040: using guessed type char _bss_start;

//----- (08048630) --------------------------------------------------------
int frame_dummy()
{
  return register_tm_clones();
}
// 8048630: could not find valid save-restore pair for ebp

//----- (08048660) --------------------------------------------------------
int bring_students_to_school()
{
  return system("/bin/sh");
}

//----- (08048690) --------------------------------------------------------
int __cdecl __noreturn main(int argc, const char **argv, const char **envp)
{
  unsigned int v3; // [esp+5Ch] [ebp-1Ch]
  char s[7]; // [esp+61h] [ebp-17h]
  int v5; // [esp+68h] [ebp-10h]

  v5 = 0;
  alarm(0x3Cu);
  setvbuf(stdin, 0, 2, 0);
  setvbuf(stdout, 0, 2, 0);
  printf("Call> ");
  memset(s, 0, 7u);
  fgets(s, 7, stdin);
  s[strcspn(s, "\n")] = 0;
  v3 = strtoul(s, 0, 10);
  switch ( v3 )
  {
    case 1u:
      student_1();
      break;
    case 2u:
      student_2();
      break;
    case 3u:
      student_3();
      break;
    case 4u:
      student_4();
      break;
    case 5u:
      student_5();
      break;
    case 0x7A69u:
      principal();
      break;
    default:
      puts("No such student");
      break;
  }
  exit(0);
}
// 8048690: using guessed type char s[7];

//----- (080488E0) --------------------------------------------------------
int student_1()
{
  return puts("Student 1 - present");
}

//----- (08048910) --------------------------------------------------------
int student_2()
{
  return puts("Student 2 - present");
}

//----- (08048940) --------------------------------------------------------
int student_3()
{
  return puts("Student 3 - present");
}

//----- (08048970) --------------------------------------------------------
int student_4()
{
  return puts("Student 4 - present");
}

//----- (080489A0) --------------------------------------------------------
int student_5()
{
  return puts("Student 5 - present");
}

//----- (080489D0) --------------------------------------------------------
int principal()
{
  char s[44]; // [esp+2Ch] [ebp-2Ch]

  memset(s, 0, 0x20u);
  printf("Leave a message for the principal, please: \n");
  fgets(s, 64, stdin);
  s[strcspn(s, "\n")] = 0;
  return printf("Principal got your message %s\n", s);
}
// 80489D0: using guessed type char s[44];

//----- (08048AA0) --------------------------------------------------------
void _libc_csu_init(void)
{
  int v0; // esi
  int v1; // edi

  init_proc();
  v0 = &_do_global_dtors_aux_fini_array_entry - _frame_dummy_init_array_entry;
  if ( v0 )
  {
    v1 = 0;
    do
      _frame_dummy_init_array_entry[v1++]();
    while ( v0 != v1 );
  }
}
// 8049EF8: using guessed type int (*_frame_dummy_init_array_entry[2])();
// 8049EFC: using guessed type int (*_do_global_dtors_aux_fini_array_entry)();

//----- (08048B04) --------------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 18 function(s)"
