/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
__int64 sub_4008D0();
// void free(void *ptr);
// int puts(const char *s);
// int fclose(FILE *stream);
// char *strchr(const char *s, int c);
// int printf(const char *format, ...);
// void *memset(void *s, int c, size_t n);
// unsigned int alarm(unsigned int seconds);
// size_t strcspn(const char *s, const char *reject);
// char *fgets(char *s, int n, FILE *stream);
// int getchar(void);
// int fflush(FILE *stream);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// FILE *fopen(const char *filename, const char *modes);
// void perror(const char *s);
// unsigned __int64 strtoul(const char *nptr, char **endptr, int base);
// __ssize_t getline(char **lineptr, size_t *n, FILE *stream);
// void __noreturn exit(int status);
// unsigned int sleep(unsigned int seconds);
signed __int64 sub_400A30();
signed __int64 sub_400AB0();
__int64 sub_400AD0();
void __fastcall __noreturn main(__int64 a1, char **a2, char **a3);
signed __int64 sub_400E30();
signed __int64 sub_400EA0();
signed __int64 sub_400F10();
char *sub_400F80();
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *off_601DF8[2])() = { &sub_400AD0, &sub_400AB0 }; // weak
__int64 (__fastcall *off_601E00)() = &sub_400AB0; // weak
__int64 (*qword_602010)(void) = NULL; // weak
_UNKNOWN unk_6020B8; // weak
_UNKNOWN unk_6020BF; // weak
FILE *stdout; // idb
FILE *stdin; // idb
char byte_6020D8; // weak


//----- (00000000004008B0) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (__int64 (**)(void))_gmon_start__();
  return result;
}
// 602178: using guessed type __int64 _gmon_start__(void);

//----- (00000000004008D0) ----------------------------------------------------
__int64 sub_4008D0()
{
  return qword_602010();
}
// 602010: using guessed type __int64 (*qword_602010)(void);

//----- (0000000000400A00) ----------------------------------------------------
#error "400A06: positive sp value has been found (funcsize=3)"

//----- (0000000000400A30) ----------------------------------------------------
signed __int64 sub_400A30()
{
  signed __int64 result; // rax

  result = &unk_6020BF - &unk_6020B8;
  if ( (unsigned __int64)(&unk_6020BF - &unk_6020B8) > 0xE )
    result = 0LL;
  return result;
}

//----- (0000000000400AB0) ----------------------------------------------------
signed __int64 sub_400AB0()
{
  signed __int64 result; // rax

  if ( !byte_6020D8 )
  {
    result = sub_400A30();
    byte_6020D8 = 1;
  }
  return result;
}
// 6020D8: using guessed type char byte_6020D8;

//----- (0000000000400AD0) ----------------------------------------------------
__int64 sub_400AD0()
{
  return 0LL;
}

//----- (0000000000400B00) ----------------------------------------------------
void __fastcall __noreturn main(__int64 a1, char **a2, char **a3)
{
  const char *v3; // rdi
  bool v4; // [rsp+2Bh] [rbp-95h]
  __int64 v5; // [rsp+50h] [rbp-70h]
  char nptr[5]; // [rsp+5Bh] [rbp-65h]
  unsigned __int64 v7; // [rsp+60h] [rbp-60h]
  int v8; // [rsp+6Ch] [rbp-54h]
  char s[32]; // [rsp+70h] [rbp-50h]
  signed __int64 (*v10)(); // [rsp+90h] [rbp-30h]
  signed __int64 (*v11)(); // [rsp+98h] [rbp-28h]
  signed __int64 (*v12)(); // [rsp+A0h] [rbp-20h]
  void *ptr; // [rsp+B0h] [rbp-10h]
  int v14; // [rsp+BCh] [rbp-4h]

  v14 = 0;
  alarm(0x3Cu);
  setvbuf(stdin, 0LL, 2, 0LL);
  setvbuf(stdout, 0LL, 2, 0LL);
  ptr = sub_400F80();
  v10 = sub_400E30;
  v11 = sub_400EA0;
  v12 = sub_400F10;
  memset(s, 0, 0x20uLL);
  printf("Your name? > ", 0LL);
  if ( !fgets(s, 32, stdin) )
  {
    perror("Failed reading player name");
    free(ptr);
    ptr = 0LL;
    exit(1);
  }
  if ( strchr(s, 10) )
  {
    s[strcspn(s, "\n")] = 0;
  }
  else
  {
    do
    {
      v8 = getchar();
      v4 = 0;
      if ( v8 != -1 )
        v4 = v8 != 10;
    }
    while ( v4 );
  }
  v7 = 0LL;
  memset(nptr, 0, 5uLL);
  v3 = "Let's play";
  puts("Let's play");
  while ( 1 )
  {
    v5 = ((__int64 (__fastcall *)(const char *, _QWORD))*(&v10 + v7))(v3, 0LL);
    printf("What number was on the screen? ");
    if ( !fgets(nptr, 5, stdin) )
      break;
    nptr[strcspn(nptr, "\n")] = 0;
    if ( strtoul(nptr, 0LL, 10) != v5 )
    {
      puts("Bad memory!");
      free(ptr);
      ptr = 0LL;
      exit(0);
    }
    puts("Good memory!");
    v3 = (const char *)(v7++ + 1);
    if ( v7 >= 3 )
    {
      printf("You have a very good memory ", 0LL);
      printf(s);
      puts("\nBye!");
      free(ptr);
      ptr = 0LL;
      exit(0);
    }
  }
  perror("Failed reading user number");
  free(ptr);
  ptr = 0LL;
  exit(1);
}
// 400B00: using guessed type char s[32];
// 400B00: using guessed type char nptr[5];

//----- (0000000000400E30) ----------------------------------------------------
signed __int64 sub_400E30()
{
  printf("%zu", 42LL);
  fflush(stdout);
  sleep(1u);
  printf("\r");
  return 42LL;
}

//----- (0000000000400EA0) ----------------------------------------------------
signed __int64 sub_400EA0()
{
  printf("%zu", 77LL);
  fflush(stdout);
  sleep(1u);
  printf("\r");
  return 77LL;
}

//----- (0000000000400F10) ----------------------------------------------------
signed __int64 sub_400F10()
{
  printf("%zu", 111LL);
  fflush(stdout);
  sleep(1u);
  printf("\r");
  return 111LL;
}

//----- (0000000000400F80) ----------------------------------------------------
char *sub_400F80()
{
  size_t v0; // rax
  char *lineptr; // [rsp+18h] [rbp-18h]
  size_t n; // [rsp+20h] [rbp-10h]
  FILE *stream; // [rsp+28h] [rbp-8h]

  stream = fopen("/home/memo/identity.txt", "r");
  if ( !stream )
  {
    perror("Failed opening identity file");
    exit(1);
  }
  n = 0LL;
  lineptr = 0LL;
  if ( getline(&lineptr, &n, stream) == -1 )
  {
    fclose(stream);
    perror("Failed reading identity");
    exit(1);
  }
  fclose(stream);
  v0 = strcspn(lineptr, "\n");
  lineptr[v0] = 0;
  return lineptr;
}

//----- (0000000000401050) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13
  signed __int64 v4; // rbp
  __int64 v5; // rbx

  v3 = a3;
  v4 = &off_601E00 - off_601DF8;
  init_proc();
  if ( v4 )
  {
    v5 = 0LL;
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))off_601DF8[v5++])(a1, a2, v3);
    while ( v4 != v5 );
  }
}
// 601DF8: using guessed type __int64 (__fastcall *off_601DF8[2])();
// 601E00: using guessed type __int64 (__fastcall *off_601E00)();

//----- (00000000004010C4) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 13 function(s)"
