/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2017 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//----- (08048740) --------------------------------------------------------
int sub_8048740()
{
  int result; // eax

  result = &unk_804A05B - &unk_804A058;
  if ( (unsigned int)(&unk_804A05B - &unk_804A058) > 6 )
    result = 0;
  return result;
}
// 8048740: could not find valid save-restore pair for ebp

//----- (080487B0) --------------------------------------------------------
int sub_80487B0()
{
  int result; // eax

  if ( !byte_804A068 )
  {
    result = sub_8048740();
    byte_804A068 = 1;
  }
  return result;
}
// 80487B0: could not find valid save-restore pair for ebp
// 804A068: using guessed type char byte_804A068;

//----- (080487D0) --------------------------------------------------------
int sub_80487D0()
{
  return 0;
}
// 80487D0: could not find valid save-restore pair for ebp

//----- (0test_pass) --------------------------------------------------------
int __cdecl test_passe(const char *pass)
{
  size_t v1; // eax
  const char *s1; // ST18_4
  size_t v3; // eax
  char *dest; // [esp+48h] [ebp-40h]
  int v6; // [esp+4Ch] [ebp-3Ch]
  FILE *stream; // [esp+50h] [ebp-38h]
  char s; // [esp+54h] [ebp-34h]
  int v9; // [esp+74h] [ebp-14h]
  const char *vpass; // [esp+78h] [ebp-10h]

  vpass = pass;
  v9 = 0;
  memset(&s, 0, 0x20u);
  stream = fopen("/home/party/orgs_password.txt", "r");
  if ( !stream )
  {
    perror("Failed opening organisers password file");
    exit(1);
  }
  v6 = 0;
  dest = 0;
  if ( getline(&dest, &v6, stream) == -1 )
  {
    fclose(stream);
    perror("Failed organisers password");
    exit(1);
  }
  fclose(stream);
  v1 = strcspn(dest, "\n");
  dest[v1] = 0;
  strcpy(&s, vpass);
  s1 = dest;
  v3 = strlen(dest);
  if ( !strncmp(s1, &s, v3) )
  {
    puts("Good password. Now you'll get your ticket...");
    puts("Ticket id: timctf{0112-3581-3213-4558-9144}");
  }
  else
  {
    puts("Bad password. No ticket, go home!");
  }
  free(dest);
  return v9;
}
// 80485E0: using guessed type int __cdecl getline(_DWORD, _DWORD, _DWORD);

//----- (080489C0) --------------------------------------------------------
void __cdecl __noreturn main()
{
  char v0; // [esp+58h] [ebp-10h]
  const char *v1; // [esp+5Ch] [ebp-Ch]
  int v2; // [esp+60h] [ebp-8h]

  v2 = 0;
  alarm(0x3Cu);
  setvbuf(stdin, 0, 2, 0);
  setvbuf(stdout, 0, 2, 0);
  puts("***^^^ STaR_C_PartY ^^^***");
  puts("-- Welcome to the party --");
  pass = 0;
  printf("Password: ");
  if ( getline(&pass, &size, stdin) == -1 )
  {
    perror("Failed reading user password");
    exit(1);
  }
  if ( test_passe(pass) == -1059127554 )
  {
    puts("Oh, you're VIP, here's the special VIP ticket:");
    system("cat /home/party/flag");
  }
  exit(0);
}
