/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// int __fastcall std::ostream::operator<<(_QWORD, _QWORD); weak
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// _QWORD std::ios_base::Init::Init(std::ios_base::Init *this); idb
// ssize_t read(int fd, void *buf, size_t nbytes);
// void *malloc(size_t size);
// int __fastcall __cxa_atexit(_QWORD, _QWORD, _QWORD); weak
_QWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this); // weak
// int __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD); weak
// void free(void *ptr);
// int __fastcall std::istream::operator>>(_QWORD, _QWORD); weak
// int __fastcall std::ostream::operator<<(_QWORD, _QWORD); weak
// ssize_t write(int fd, const void *buf, size_t n);
// int _gmon_start__(void); weak
__int64 sub_400A00();
__int64 sub_400C00();
signed int sub_400DD0();
signed int sub_400E50();
int sub_400E70();
__int64 sub_400EA0();
__int64 sub_401300();
__int64 sub_401680();
__int64 sub_402060();
__int64 __fastcall main(__int64 a1, char **a2, char **a3);
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

// extern _UNKNOWN std::endl<char,std::char_traits<char>>; weak
__int64 (__fastcall *off_604DD8[3])() = { &sub_400E70, &sub_400C00, &sub_400E50 }; // weak
__int64 (__fastcall *off_604DE8)() = &sub_400E50; // weak
_UNKNOWN unk_605090; // weak
_UNKNOWN std::cin; // weak
FILE *stdin; // idb
_UNKNOWN std::cout; // weak
FILE *stdout; // idb
char byte_6052F8; // weak
_UNKNOWN unk_605300; // weak
void *buf; // idb
int dword_605630; // weak
int dword_605634; // weak
int dword_605638; // weak
int dword_60563C; // weak
int dword_605640; // weak
int dword_605644; // weak
int dword_605648; // weak
int dword_60564C; // weak
int dword_605650; // weak
int dword_605654; // weak
int dword_605658; // weak
int dword_60565C; // weak
int dword_605660; // weak
int dword_605664; // weak
int dword_605668; // weak
// extern _UNKNOWN __gmon_start__; weak


//----- (00000000004008E0) ----------------------------------------------------
int init_proc()
{
  void *v0; // rax@1

  v0 = &__gmon_start__;
  if ( &__gmon_start__ )
    LODWORD(v0) = _gmon_start__();
  return (unsigned __int64)v0;
}
// 4009F0: using guessed type int _gmon_start__(void);

//----- (0000000000400A00) ----------------------------------------------------
__int64 sub_400A00()
{
  __int64 result; // rax@5
  signed int v1; // eax@7
  signed int v2; // ecx@10
  int v3; // er9@10
  signed int v4; // [sp+20h] [bp-20h]@1
  bool v5; // [sp+26h] [bp-1Ah]@1
  bool v6; // [sp+27h] [bp-19h]@1

  v5 = (((_BYTE)dword_605640 - 1) * (_BYTE)dword_605640 & 1) == 0;
  v6 = dword_605650 < 10;
  v4 = -810912642;
  do
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( v4 == -1546911995 )
        {
          std::ios_base::Init::Init((std::ios_base::Init *)&unk_605300);
          __cxa_atexit(std::ios_base::Init::~Init, &unk_605300, &unk_605090);
          v2 = 463848191;
          v3 = ((_BYTE)dword_605640 - 23 + 22) * (_BYTE)dword_605640 & 1;
          if ( ((unsigned __int8)((dword_605650 < 10) ^ (v3 == 0)) | (dword_605650 < 10 && v3 == 0)) & 1 )
            v2 = 553970543;
          v4 = v2;
        }
        if ( v4 != -810912642 )
          break;
        v1 = 463848191;
        if ( (~((unsigned __int8)~v6 | (unsigned __int8)~v5) & 1 | (unsigned __int8)(v6 ^ v5)) & 1 )
          v1 = -1546911995;
        v4 = v1;
      }
      if ( v4 != 463848191 )
        break;
      std::ios_base::Init::Init((std::ios_base::Init *)&unk_605300);
      v4 = -1546911995;
      __cxa_atexit(std::ios_base::Init::~Init, &unk_605300, &unk_605090);
    }
    result = (unsigned int)(v4 - 553970543);
  }
  while ( v4 != 553970543 );
  return result;
}
// 400970: using guessed type int __fastcall __cxa_atexit(_QWORD, _QWORD, _QWORD);
// 400980: using guessed type _QWORD __cdecl std::ios_base::Init::~Init(std::ios_base::Init *__hidden this);
// 605640: using guessed type int dword_605640;
// 605650: using guessed type int dword_605650;

//----- (0000000000400C00) ----------------------------------------------------
__int64 sub_400C00()
{
  __int64 result; // rax@2
  signed int v1; // eax@7
  signed int v2; // eax@10
  signed int v3; // [sp+20h] [bp-20h]@1
  bool v4; // [sp+26h] [bp-1Ah]@1
  bool v5; // [sp+27h] [bp-19h]@1

  v4 = (((_BYTE)dword_60563C - 1) * (_BYTE)dword_60563C & 1) == 0;
  v5 = dword_60565C < 10;
  v3 = -100760401;
  while ( 1 )
  {
    result = (unsigned int)v3;
    if ( v3 == -1558669708 )
      break;
    switch ( v3 )
    {
      case -100760401:
        v1 = 1988521573;
        if ( ((unsigned __int8)(v5 ^ v4) | (v5 && v4)) & 1 )
          v1 = 1703137465;
        v3 = v1;
        break;
      case 1703137465:
        sub_400A00();
        v2 = 1988521573;
        if ( (~((unsigned __int8)~(dword_60565C < 10) | (unsigned __int8)~((((_BYTE)dword_60563C - 1)
                                                                          * (_BYTE)dword_60563C & 1) == 0)) & 1 | (unsigned __int8)(~(dword_60565C < 10) ^ ~((((_BYTE)dword_60563C - 1) * (_BYTE)dword_60563C & 1) == 0))) & 1 )
          v2 = -1558669708;
        v3 = v2;
        break;
      case 1988521573:
        sub_400A00();
        v3 = 1703137465;
        break;
    }
  }
  return result;
}
// 60563C: using guessed type int dword_60563C;
// 60565C: using guessed type int dword_60565C;

//----- (0000000000400DA0) ----------------------------------------------------
#error "400DA6: positive sp value has been found (funcsize=3)"

//----- (0000000000400DD0) ----------------------------------------------------
signed int sub_400DD0()
{
  return 7;
}

//----- (0000000000400E50) ----------------------------------------------------
signed int sub_400E50()
{
  signed int result; // eax@2

  if ( !byte_6052F8 )
  {
    result = sub_400DD0();
    byte_6052F8 = 1;
  }
  return result;
}
// 6052F8: using guessed type char byte_6052F8;

//----- (0000000000400E70) ----------------------------------------------------
int sub_400E70()
{
  return 0;
}

//----- (0000000000400EA0) ----------------------------------------------------
__int64 sub_400EA0()
{
  __int64 result; // rax@5
  signed int v1; // eax@7
  __int64 v2; // rax@10
  __int64 v3; // rax@10
  __int64 v4; // rax@10
  __int64 v5; // rax@10
  size_t v6; // rdi@10
  __int64 v7; // rax@10
  __int64 v8; // rax@10
  __int64 v9; // rax@10
  void *v10; // rsi@10
  size_t v11; // rdx@10
  int v12; // eax@10
  signed int v13; // edi@10
  void *v14; // rdx@10
  int v15; // er11@10
  __int64 v16; // rax@14
  __int64 v17; // rax@14
  __int64 v18; // rax@14
  __int64 v19; // rax@14
  size_t v20; // rdi@14
  __int64 v21; // rax@14
  __int64 v22; // rax@14
  __int64 v23; // rax@14
  void *bufskill2; // rsi@14
  size_t v25; // rdx@14
  int v26; // eax@14
  void *bufskill; // rdx@14
  __int64 v28; // [sp+0h] [bp-D0h]@10
  __int64 v29; // [sp+8h] [bp-C8h]@14
  __int64 v30; // [sp+10h] [bp-C0h]@14
  __int64 v31; // [sp+18h] [bp-B8h]@14
  __int64 v32; // [sp+20h] [bp-B0h]@14
  __int64 v33; // [sp+28h] [bp-A8h]@14
  __int64 *v34; // [sp+30h] [bp-A0h]@14
  void **ptrbufskill; // [sp+38h] [bp-98h]@14
  __int64 *v36; // [sp+40h] [bp-90h]@14
  __int64 v37; // [sp+48h] [bp-88h]@10
  __int64 v38; // [sp+50h] [bp-80h]@10
  __int64 v39; // [sp+58h] [bp-78h]@10
  __int64 v40; // [sp+60h] [bp-70h]@10
  __int64 v41; // [sp+68h] [bp-68h]@10
  __int64 *v42; // [sp+70h] [bp-60h]@10
  void **v43; // [sp+78h] [bp-58h]@10
  __int64 *v44; // [sp+80h] [bp-50h]@10
  int v45; // [sp+8Ch] [bp-44h]@5
  int v46; // [sp+90h] [bp-40h]@4
  int v47; // [sp+94h] [bp-3Ch]@3
  int v48; // [sp+98h] [bp-38h]@2
  int v49; // [sp+9Ch] [bp-34h]@2
  int v50; // [sp+A0h] [bp-30h]@1
  bool v51; // [sp+A6h] [bp-2Ah]@1
  bool v52; // [sp+A7h] [bp-29h]@1

  v51 = (((_BYTE)dword_605664 - 1) * (_BYTE)dword_605664 & 1) == 0;
  v52 = dword_605634 < 10;
  v50 = -1643514896;
  do
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          v49 = v50;
          v48 = v50 + 1643514896;
          if ( v50 != -1643514896 )
            break;
          v1 = 767677869;
          if ( ((unsigned __int8)(v52 ^ v51) | (v52 && v51)) & 1 )
            v1 = -1554156682;
          v50 = v1;
        }
        v47 = v49 + 1554156682;
        if ( v49 != -1554156682 )
          break;
        *((_DWORD *)&v28 - 4) = 0;
        v44 = &v28 - 2;
        v43 = (void **)(&v28 - 2);
        v42 = &v28 - 2;
        LODWORD(v2) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]SPECIFY THE SIZE OF ZEALOT");
        LODWORD(v3) = std::ostream::operator<<(v2, &std::endl<char,std::char_traits<char>>);
        v41 = v3;
        LODWORD(v4) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
        v40 = v4;
        LODWORD(v5) = std::istream::operator>>(&std::cin, v42);
        v6 = *(_DWORD *)v42;
        v39 = v5;
        *v43 = malloc(v6);
        LODWORD(v7) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]GIVE SOME SKILLS TO ZEALOT");
        LODWORD(v8) = std::ostream::operator<<(v7, &std::endl<char,std::char_traits<char>>);
        v38 = v8;
        LODWORD(v9) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
        v10 = *v43;
        v11 = *(_DWORD *)v42;
        v37 = v9;
        v12 = read(0, v10, v11);
        v13 = 767677869;
        *(_DWORD *)v44 = v12;
        v14 = *v43;
        v15 = dword_605630++;
        *(&buf + v15) = v14;
        if ( (~((unsigned __int8)~(dword_605634 < 10) | (unsigned __int8)~((((_BYTE)dword_605664 - 1)
                                                                          * (_BYTE)dword_605664 & 1) == 0)) & 1 | (unsigned __int8)(~(dword_605634 < 10) ^ ~((((_BYTE)dword_605664 - 1) * (_BYTE)dword_605664 & 1) == 0))) & 1 )
          v13 = 938701465;
        v50 = v13;
      }
      v46 = v49 - 767677869;
      if ( v49 != 767677869 )
        break;
      *((_DWORD *)&v28 - 4) = 0;
      v36 = &v28 - 2;
      ptrbufskill = (void **)(&v28 - 2);
      v34 = &v28 - 2;
      LODWORD(v16) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]SPECIFY THE SIZE OF ZEALOT");
      LODWORD(v17) = std::ostream::operator<<(v16, &std::endl<char,std::char_traits<char>>);
      v33 = v17;
      LODWORD(v18) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
      v32 = v18;
      LODWORD(v19) = std::istream::operator>>(&std::cin, v34);
      v20 = *(_DWORD *)v34;
      v31 = v19;
      *ptrbufskill = malloc(v20);
      LODWORD(v21) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]GIVE SOME SKILLS TO ZEALOT");
      LODWORD(v22) = std::ostream::operator<<(v21, &std::endl<char,std::char_traits<char>>);
      v30 = v22;
      LODWORD(v23) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
      bufskill2 = *ptrbufskill;
      v25 = *(_DWORD *)v34;
      v29 = v23;
      v26 = read(0, bufskill2, v25);
      *(_DWORD *)v36 = v26;
      bufskill = *ptrbufskill;
      LODWORD(v20) = dword_605630;
      dword_605630 = dword_605630 - 1634993326 + 1634993327;
      *(&buf + (signed int)v20) = bufskill;
      v50 = -1554156682;
    }
    result = (unsigned int)(v49 - 938701465);
    v45 = v49 - 938701465;
  }
  while ( v49 != 938701465 );
  return result;
}
// 400990: using guessed type int __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD);
// 4009B0: using guessed type int __fastcall std::istream::operator>>(_QWORD, _QWORD);
// 4009C0: using guessed type int __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 605630: using guessed type int dword_605630;
// 605634: using guessed type int dword_605634;
// 605664: using guessed type int dword_605664;

//----- (0000000000401300) ----------------------------------------------------
__int64 sub_401300()
{
  __int64 result; // rax@2
  signed int v1; // eax@7
  __int64 v2; // rax@10
  __int64 v3; // rax@10
  __int64 v4; // rax@10
  __int64 v5; // rax@10
  __int64 v6; // rax@10
  __int64 v7; // rax@10
  void *v8; // rdi@10
  __int64 v9; // rax@10
  __int64 v10; // rax@10
  signed int v11; // ecx@10
  __int64 v12; // rax@14
  __int64 v13; // rax@14
  __int64 v14; // rax@14
  __int64 v15; // rax@14
  __int64 v16; // rax@14
  __int64 v17; // rax@14
  void *v18; // rdi@14
  __int64 v19; // rax@14
  __int64 v20; // rax@14
  __int64 v21; // [sp+0h] [bp-B0h]@10
  __int64 v22; // [sp+8h] [bp-A8h]@14
  __int64 v23; // [sp+10h] [bp-A0h]@14
  __int64 v24; // [sp+18h] [bp-98h]@14
  __int64 v25; // [sp+20h] [bp-90h]@14
  __int64 v26; // [sp+28h] [bp-88h]@14
  __int64 *v27; // [sp+30h] [bp-80h]@14
  __int64 v28; // [sp+38h] [bp-78h]@12
  __int64 v29; // [sp+40h] [bp-70h]@10
  __int64 v30; // [sp+48h] [bp-68h]@10
  __int64 v31; // [sp+50h] [bp-60h]@10
  __int64 v32; // [sp+58h] [bp-58h]@10
  __int64 *v33; // [sp+60h] [bp-50h]@10
  unsigned int v34; // [sp+6Ch] [bp-44h]@5
  unsigned int v35; // [sp+70h] [bp-40h]@4
  unsigned int v36; // [sp+74h] [bp-3Ch]@3
  unsigned int v37; // [sp+78h] [bp-38h]@2
  unsigned int v38; // [sp+7Ch] [bp-34h]@2
  unsigned int v39; // [sp+80h] [bp-30h]@1
  bool v40; // [sp+86h] [bp-2Ah]@1
  bool v41; // [sp+87h] [bp-29h]@1

  v40 = (((_BYTE)dword_605644 - 1) * (_BYTE)dword_605644 & 1) == 0;
  v41 = dword_605654 < 10;
  v39 = 409170129;
  while ( 1 )
  {
    result = v39;
    v38 = v39;
    v37 = v39 + 62200835;
    if ( v39 == -62200835 )
      break;
    v36 = v38 - 409170129;
    if ( v38 == 409170129 )
    {
      v1 = 2043564160;
      if ( ((unsigned __int8)(v41 ^ v40) | (v41 && v40)) & 1 )
        v1 = 458914072;
      v39 = v1;
    }
    else
    {
      v35 = v38 - 458914072;
      if ( v38 == 458914072 )
      {
        *((_DWORD *)&v21 - 4) = 0;
        v33 = &v21 - 2;
        LODWORD(v2) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]WHICH ONE DO YOU WANT TO DESTROY?");
        LODWORD(v3) = std::ostream::operator<<(v2, &std::endl<char,std::char_traits<char>>);
        v32 = v3;
        LODWORD(v4) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
        v31 = v4;
        LODWORD(v5) = std::istream::operator>>(&std::cin, v33);
        v30 = v5;
        LODWORD(v6) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]BREAKING....");
        LODWORD(v7) = std::ostream::operator<<(v6, &std::endl<char,std::char_traits<char>>);
        v8 = *(&buf + *(_DWORD *)v33);
        v29 = v7;
        free(v8);
        LODWORD(v9) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]SUCCESSFUL!");
        LODWORD(v10) = std::ostream::operator<<(v9, &std::endl<char,std::char_traits<char>>);
        v11 = 2043564160;
        if ( (~((unsigned __int8)~(dword_605654 < 10) | (unsigned __int8)~((((_BYTE)dword_605644 - 1)
                                                                          * (_BYTE)dword_605644 & 1) == 0)) & 1 | (unsigned __int8)(~(dword_605654 < 10) ^ ~((((_BYTE)dword_605644 - 1) * (_BYTE)dword_605644 & 1) == 0))) & 1 )
          v11 = -62200835;
        v39 = v11;
        v28 = v10;
      }
      else
      {
        v34 = v38 - 2043564160;
        if ( v38 == 2043564160 )
        {
          *((_DWORD *)&v21 - 4) = 0;
          v27 = &v21 - 2;
          LODWORD(v12) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]WHICH ONE DO YOU WANT TO DESTROY?");
          LODWORD(v13) = std::ostream::operator<<(v12, &std::endl<char,std::char_traits<char>>);
          v26 = v13;
          LODWORD(v14) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
          v25 = v14;
          LODWORD(v15) = std::istream::operator>>(&std::cin, v27);
          v24 = v15;
          LODWORD(v16) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]BREAKING....");
          LODWORD(v17) = std::ostream::operator<<(v16, &std::endl<char,std::char_traits<char>>);
          v18 = *(&buf + *(_DWORD *)v27);
          v23 = v17;
          free(v18);
          LODWORD(v19) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]SUCCESSFUL!");
          LODWORD(v20) = std::ostream::operator<<(v19, &std::endl<char,std::char_traits<char>>);
          v39 = 458914072;
          v22 = v20;
        }
      }
    }
  }
  return result;
}
// 400990: using guessed type int __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD);
// 4009B0: using guessed type int __fastcall std::istream::operator>>(_QWORD, _QWORD);
// 4009C0: using guessed type int __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 605644: using guessed type int dword_605644;
// 605654: using guessed type int dword_605654;

//----- (0000000000401680) ----------------------------------------------------
__int64 sub_401680()
{
  __int64 result; // rax@3
  signed int v1; // eax@19
  __int64 v2; // rax@22
  __int64 v3; // rax@22
  __int64 v4; // rax@22
  __int64 v5; // rax@22
  signed int v6; // ecx@22
  signed int v7; // eax@25
  signed int v8; // eax@28
  __int64 v9; // rax@31
  __int64 v10; // rax@31
  __int64 v11; // rax@31
  __int64 v12; // rax@31
  __int64 v13; // rax@31
  __int64 v14; // rax@31
  __int64 v15; // rax@31
  void *v16; // rsi@31
  size_t v17; // rdx@31
  int v18; // eax@31
  __int64 v19; // rax@31
  __int64 v20; // rax@31
  __int64 v21; // rax@31
  __int64 v22; // rax@31
  __int64 v23; // rax@31
  __int64 v24; // rax@31
  signed int v25; // er8@31
  bool v26; // r15@31
  signed int v27; // eax@35
  bool v28; // r9@35
  __int64 v29; // rax@38
  __int64 v30; // rax@38
  signed int v31; // ecx@38
  signed int v32; // eax@42
  signed int v33; // eax@45
  __int64 v34; // rax@49
  __int64 v35; // rax@49
  __int64 v36; // rax@49
  __int64 v37; // rax@49
  __int64 v38; // rax@50
  __int64 v39; // rax@50
  __int64 v40; // rax@50
  __int64 v41; // rax@50
  __int64 v42; // rax@50
  __int64 v43; // rax@50
  __int64 v44; // rax@50
  void *v45; // rsi@50
  size_t v46; // rdx@50
  int v47; // eax@50
  __int64 v48; // rax@50
  __int64 v49; // rax@50
  __int64 v50; // rax@50
  __int64 v51; // rax@50
  __int64 v52; // rax@50
  __int64 v53; // rax@50
  __int64 v54; // rax@51
  __int64 v55; // rax@51
  __int64 v56; // [sp+0h] [bp-150h]@22
  __int64 v57; // [sp+8h] [bp-148h]@50
  __int64 v58; // [sp+10h] [bp-140h]@50
  __int64 v59; // [sp+18h] [bp-138h]@50
  __int64 v60; // [sp+20h] [bp-130h]@50
  __int64 v61; // [sp+28h] [bp-128h]@50
  __int64 v62; // [sp+30h] [bp-120h]@50
  __int64 v63; // [sp+38h] [bp-118h]@50
  __int64 v64; // [sp+40h] [bp-110h]@49
  __int64 v65; // [sp+48h] [bp-108h]@49
  __int64 v66; // [sp+50h] [bp-100h]@49
  __int64 *v67; // [sp+58h] [bp-F8h]@49
  __int64 v68; // [sp+60h] [bp-F0h]@40
  __int64 v69; // [sp+68h] [bp-E8h]@33
  __int64 v70; // [sp+70h] [bp-E0h]@31
  __int64 v71; // [sp+78h] [bp-D8h]@31
  __int64 v72; // [sp+80h] [bp-D0h]@31
  __int64 v73; // [sp+88h] [bp-C8h]@31
  __int64 v74; // [sp+90h] [bp-C0h]@31
  __int64 v75; // [sp+98h] [bp-B8h]@31
  __int64 v76; // [sp+A0h] [bp-B0h]@24
  __int64 v77; // [sp+A8h] [bp-A8h]@22
  __int64 v78; // [sp+B0h] [bp-A0h]@22
  int v79; // [sp+BCh] [bp-94h]@17
  int v80; // [sp+C0h] [bp-90h]@16
  int v81; // [sp+C4h] [bp-8Ch]@15
  int v82; // [sp+C8h] [bp-88h]@14
  int v83; // [sp+CCh] [bp-84h]@13
  int v84; // [sp+D0h] [bp-80h]@12
  int v85; // [sp+D4h] [bp-7Ch]@11
  int v86; // [sp+D8h] [bp-78h]@10
  int v87; // [sp+DCh] [bp-74h]@9
  int v88; // [sp+E0h] [bp-70h]@8
  int v89; // [sp+E4h] [bp-6Ch]@7
  int v90; // [sp+E8h] [bp-68h]@6
  int v91; // [sp+ECh] [bp-64h]@5
  int v92; // [sp+F0h] [bp-60h]@4
  int v93; // [sp+F4h] [bp-5Ch]@3
  int v94; // [sp+F8h] [bp-58h]@2
  int v95; // [sp+FCh] [bp-54h]@2
  int v96; // [sp+100h] [bp-50h]@1
  bool v97; // [sp+106h] [bp-4Ah]@1
  bool v98; // [sp+107h] [bp-49h]@1
  __int64 *v99; // [sp+108h] [bp-48h]@22
  __int64 *v100; // [sp+110h] [bp-40h]@22
  __int64 *v101; // [sp+118h] [bp-38h]@22
  bool v102; // [sp+127h] [bp-29h]@22

  v97 = (((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0;
  v98 = dword_605638 < 10;
  v96 = 1531622769;
  while ( 1 )
  {
    while ( 1 )
    {
      v95 = v96;
      v94 = v96 + 1750917296;
      if ( v96 != -1750917296 )
        break;
      v7 = 1440000704;
      if ( v102 )
        v7 = 1994344819;
      v96 = v7;
    }
    result = (unsigned int)(v95 + 1661904105);
    v93 = v95 + 1661904105;
    if ( v95 == -1661904105 )
      break;
    v92 = v95 + 1620987206;
    if ( v95 == -1620987206 )
    {
      LODWORD(v29) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]HMMM....");
      LODWORD(v30) = std::ostream::operator<<(v29, &std::endl<char,std::char_traits<char>>);
      v31 = -1373461622;
      if ( ((unsigned __int8)((dword_605638 < 10) ^ ((((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) | (dword_605638 < 10 && (((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) & 1 )
        v31 = 1265633952;
      v96 = v31;
      v68 = v30;
    }
    else
    {
      v91 = v95 + 1485262874;
      if ( v95 == -1485262874 )
      {
        v32 = 957529158;
        if ( ((unsigned __int8)((dword_605638 < 10) ^ ((((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) | (dword_605638 < 10 && (((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) & 1 )
          v32 = -862274549;
        v96 = v32;
      }
      else
      {
        v90 = v95 + 1373461622;
        if ( v95 == -1373461622 )
        {
          LODWORD(v54) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]HMMM....");
          LODWORD(v55) = std::ostream::operator<<(v54, &std::endl<char,std::char_traits<char>>);
          v96 = -1620987206;
          v56 = v55;
        }
        else
        {
          v89 = v95 + 1101471325;
          if ( v95 == -1101471325 )
          {
            v96 = -1485262874;
          }
          else
          {
            v88 = v95 + 862274549;
            if ( v95 == -862274549 )
            {
              v33 = 957529158;
              if ( ((unsigned __int8)((dword_605638 < 10) ^ ((((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) | (dword_605638 < 10 && (((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) & 1 )
                v33 = -1661904105;
              v96 = v33;
            }
            else
            {
              v87 = v95 + 833378032;
              if ( v95 == -833378032 )
              {
                LODWORD(v38) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]SPECIFY THE SIZE OF ZEALOT");
                LODWORD(v39) = std::ostream::operator<<(v38, &std::endl<char,std::char_traits<char>>);
                v63 = v39;
                LODWORD(v40) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
                v62 = v40;
                LODWORD(v41) = std::istream::operator>>(&std::cin, v100);
                v61 = v41;
                LODWORD(v42) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]GIVE SOME SKILLS TO ZEALOT");
                LODWORD(v43) = std::ostream::operator<<(v42, &std::endl<char,std::char_traits<char>>);
                v60 = v43;
                LODWORD(v44) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
                v45 = *(&buf + *(_DWORD *)v99);
                v46 = *(_DWORD *)v100;
                v59 = v44;
                v47 = read(0, v45, v46);
                *(_DWORD *)v101 = v47;
                LODWORD(v48) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]FIXED ZEALOT NUMBER:");
                LODWORD(v49) = std::ostream::operator<<(v48, *(_DWORD *)v99);
                LODWORD(v50) = std::ostream::operator<<(v49, &std::endl<char,std::char_traits<char>>);
                v58 = v50;
                LODWORD(v51) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]FIXED ZEALOT SIZE:");
                LODWORD(v52) = std::ostream::operator<<(v51, *(_DWORD *)v100);
                LODWORD(v53) = std::ostream::operator<<(v52, &std::endl<char,std::char_traits<char>>);
                v96 = 1482134899;
                v57 = v53;
              }
              else
              {
                v86 = v95 + 92990706;
                if ( v95 == -92990706 )
                {
                  v99 = &v56 - 2;
                  v100 = &v56 - 2;
                  v101 = &v56 - 2;
                  *((_DWORD *)&v56 - 4) = 0;
                  *(_DWORD *)v100 = 0;
                  LODWORD(v2) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]WHCIH ONE DO YOU WANT TO FIX ?");
                  LODWORD(v3) = std::ostream::operator<<(v2, &std::endl<char,std::char_traits<char>>);
                  v78 = v3;
                  LODWORD(v4) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
                  v77 = v4;
                  LODWORD(v5) = std::istream::operator>>(&std::cin, v99);
                  v6 = 953248117;
                  v102 = *(&buf + *(_DWORD *)v99) != 0LL;
                  if ( ((unsigned __int8)((dword_605638 < 10) ^ ((((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) | (dword_605638 < 10 && (((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) & 1 )
                    v6 = -1750917296;
                  v96 = v6;
                  v76 = v5;
                }
                else
                {
                  v85 = v95 - 953248117;
                  if ( v95 == 953248117 )
                  {
                    *((_DWORD *)&v56 - 4) = 0;
                    *((_DWORD *)&v56 - 4) = 0;
                    v67 = &v56 - 2;
                    LODWORD(v34) = std::operator<<<std::char_traits<char>>(
                                     &std::cout,
                                     "[*]WHCIH ONE DO YOU WANT TO FIX ?");
                    LODWORD(v35) = std::ostream::operator<<(v34, &std::endl<char,std::char_traits<char>>);
                    v66 = v35;
                    LODWORD(v36) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
                    v65 = v36;
                    LODWORD(v37) = std::istream::operator>>(&std::cin, v67);
                    v96 = -92990706;
                    v64 = v37;
                  }
                  else
                  {
                    v84 = v95 - 957529158;
                    if ( v95 == 957529158 )
                    {
                      v96 = -862274549;
                    }
                    else
                    {
                      v83 = v95 - 1265633952;
                      if ( v95 == 1265633952 )
                      {
                        v96 = -1485262874;
                      }
                      else
                      {
                        v82 = v95 - 1440000704;
                        if ( v95 == 1440000704 )
                        {
                          v27 = -1373461622;
                          v28 = (((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0;
                          if ( (~((unsigned __int8)~(dword_605638 < 10) | (unsigned __int8)~v28) & 1 | (unsigned __int8)((dword_605638 < 10) ^ v28)) & 1 )
                            v27 = -1620987206;
                          v96 = v27;
                        }
                        else
                        {
                          v81 = v95 - 1482134899;
                          if ( v95 == 1482134899 )
                          {
                            LODWORD(v9) = std::operator<<<std::char_traits<char>>(
                                            &std::cout,
                                            "[*]SPECIFY THE SIZE OF ZEALOT");
                            LODWORD(v10) = std::ostream::operator<<(v9, &std::endl<char,std::char_traits<char>>);
                            v75 = v10;
                            LODWORD(v11) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
                            v74 = v11;
                            LODWORD(v12) = std::istream::operator>>(&std::cin, v100);
                            v73 = v12;
                            LODWORD(v13) = std::operator<<<std::char_traits<char>>(
                                             &std::cout,
                                             "[*]GIVE SOME SKILLS TO ZEALOT");
                            LODWORD(v14) = std::ostream::operator<<(v13, &std::endl<char,std::char_traits<char>>);
                            v72 = v14;
                            LODWORD(v15) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
                            v16 = *(&buf + *(_DWORD *)v99);
                            v17 = *(_DWORD *)v100;
                            v71 = v15;
                            v18 = read(0, v16, v17);
                            *(_DWORD *)v101 = v18;
                            LODWORD(v19) = std::operator<<<std::char_traits<char>>(
                                             &std::cout,
                                             "[*]FIXED ZEALOT NUMBER:");
                            LODWORD(v20) = std::ostream::operator<<(v19, *(_DWORD *)v99);
                            LODWORD(v21) = std::ostream::operator<<(v20, &std::endl<char,std::char_traits<char>>);
                            v70 = v21;
                            LODWORD(v22) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]FIXED ZEALOT SIZE:");
                            LODWORD(v23) = std::ostream::operator<<(v22, *(_DWORD *)v100);
                            LODWORD(v24) = std::ostream::operator<<(v23, &std::endl<char,std::char_traits<char>>);
                            v25 = -833378032;
                            v26 = (((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0;
                            if ( (~((unsigned __int8)~(dword_605638 < 10) | (unsigned __int8)~v26) & 1 | (unsigned __int8)((dword_605638 < 10) ^ v26)) & 1 )
                              v25 = -1101471325;
                            v96 = v25;
                            v69 = v24;
                          }
                          else
                          {
                            v80 = v95 - 1531622769;
                            if ( v95 == 1531622769 )
                            {
                              v1 = 953248117;
                              if ( ((unsigned __int8)(v98 ^ v97) | (v98 && v97)) & 1 )
                                v1 = -92990706;
                              v96 = v1;
                            }
                            else
                            {
                              v79 = v95 - 1994344819;
                              if ( v95 == 1994344819 )
                              {
                                v8 = -833378032;
                                if ( ((unsigned __int8)((dword_605638 < 10) ^ ((((_BYTE)dword_605668 - 1)
                                                                              * (_BYTE)dword_605668 & 1) == 0)) | (dword_605638 < 10 && (((_BYTE)dword_605668 - 1) * (_BYTE)dword_605668 & 1) == 0)) & 1 )
                                  v8 = 1482134899;
                                v96 = v8;
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return result;
}
// 400910: using guessed type int __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 400990: using guessed type int __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD);
// 4009B0: using guessed type int __fastcall std::istream::operator>>(_QWORD, _QWORD);
// 4009C0: using guessed type int __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 605638: using guessed type int dword_605638;
// 605668: using guessed type int dword_605668;

//----- (0000000000402060) ----------------------------------------------------
__int64 sub_402060()
{
  __int64 result; // rax@2
  signed int v1; // eax@7
  __int64 v2; // rax@10
  __int64 v3; // rax@10
  __int64 v4; // rax@10
  __int64 v5; // rax@10
  __int64 v6; // rax@10
  __int64 v7; // rax@10
  const void *v8; // rsi@10
  ssize_t v9; // rax@10
  signed int v10; // ecx@10
  bool v11; // r14@10
  __int64 v12; // rax@14
  __int64 v13; // rax@14
  __int64 v14; // rax@14
  __int64 v15; // rax@14
  __int64 v16; // rax@14
  __int64 v17; // rax@14
  const void *v18; // rsi@14
  ssize_t v19; // rax@14
  __int64 v20; // [sp+0h] [bp-B0h]@10
  __int64 v21; // [sp+8h] [bp-A8h]@14
  __int64 v22; // [sp+10h] [bp-A0h]@14
  __int64 v23; // [sp+18h] [bp-98h]@14
  __int64 v24; // [sp+20h] [bp-90h]@14
  __int64 v25; // [sp+28h] [bp-88h]@14
  __int64 *v26; // [sp+30h] [bp-80h]@14
  __int64 v27; // [sp+38h] [bp-78h]@12
  __int64 v28; // [sp+40h] [bp-70h]@10
  __int64 v29; // [sp+48h] [bp-68h]@10
  __int64 v30; // [sp+50h] [bp-60h]@10
  __int64 v31; // [sp+58h] [bp-58h]@10
  __int64 *v32; // [sp+60h] [bp-50h]@10
  unsigned int v33; // [sp+6Ch] [bp-44h]@5
  unsigned int v34; // [sp+70h] [bp-40h]@4
  unsigned int v35; // [sp+74h] [bp-3Ch]@3
  unsigned int v36; // [sp+78h] [bp-38h]@2
  unsigned int v37; // [sp+7Ch] [bp-34h]@2
  unsigned int v38; // [sp+80h] [bp-30h]@1
  bool v39; // [sp+86h] [bp-2Ah]@1
  bool v40; // [sp+87h] [bp-29h]@1

  v39 = (((_BYTE)dword_60564C - 1) * (_BYTE)dword_60564C & 1) == 0;
  v40 = dword_605658 < 10;
  v38 = -1126288913;
  while ( 1 )
  {
    result = v38;
    v37 = v38;
    v36 = v38 + 1802141315;
    if ( v38 == -1802141315 )
      break;
    v35 = v37 + 1672220324;
    if ( v37 == -1672220324 )
    {
      *((_DWORD *)&v20 - 4) = 0;
      v32 = &v20 - 2;
      LODWORD(v2) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]WHICH ONE DO YOU WANT TO SEE?");
      LODWORD(v3) = std::ostream::operator<<(v2, &std::endl<char,std::char_traits<char>>);
      v31 = v3;
      LODWORD(v4) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
      v30 = v4;
      LODWORD(v5) = std::istream::operator>>(&std::cin, v32);
      v29 = v5;
      LODWORD(v6) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]SHOWING....");
      LODWORD(v7) = std::ostream::operator<<(v6, &std::endl<char,std::char_traits<char>>);
      v8 = *(&buf + *(_DWORD *)v32);
      v28 = v7;
      v9 = write(1, v8, 8uLL);
      v10 = 541424882;
      v11 = (((_BYTE)dword_60564C - 1) * (_BYTE)dword_60564C & 1) == 0;
      if ( (~((unsigned __int8)~(dword_605658 < 10) | (unsigned __int8)~v11) & 1 | (unsigned __int8)((dword_605658 < 10) ^ v11)) & 1 )
        v10 = -1802141315;
      v38 = v10;
      v27 = v9;
    }
    else
    {
      v34 = v37 + 1126288913;
      if ( v37 == -1126288913 )
      {
        v1 = 541424882;
        if ( (~((unsigned __int8)~v40 | (unsigned __int8)~v39) & 1 | (unsigned __int8)(v40 ^ v39)) & 1 )
          v1 = -1672220324;
        v38 = v1;
      }
      else
      {
        v33 = v37 - 541424882;
        if ( v37 == 541424882 )
        {
          *((_DWORD *)&v20 - 4) = 0;
          v26 = &v20 - 2;
          LODWORD(v12) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]WHICH ONE DO YOU WANT TO SEE?");
          LODWORD(v13) = std::ostream::operator<<(v12, &std::endl<char,std::char_traits<char>>);
          v25 = v13;
          LODWORD(v14) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
          v24 = v14;
          LODWORD(v15) = std::istream::operator>>(&std::cin, v26);
          v23 = v15;
          LODWORD(v16) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]SHOWING....");
          LODWORD(v17) = std::ostream::operator<<(v16, &std::endl<char,std::char_traits<char>>);
          v18 = *(&buf + *(_DWORD *)v26);
          v22 = v17;
          v19 = write(1, v18, 8uLL);
          v38 = -1672220324;
          v21 = v19;
        }
      }
    }
  }
  return result;
}
// 400990: using guessed type int __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD);
// 4009B0: using guessed type int __fastcall std::istream::operator>>(_QWORD, _QWORD);
// 4009C0: using guessed type int __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 60564C: using guessed type int dword_60564C;
// 605658: using guessed type int dword_605658;

//----- (00000000004023E0) ----------------------------------------------------
__int64 __fastcall main(__int64 a1, char **a2, char **a3)
{
  signed int v3; // eax@54
  int v4; // eax@57
  __int64 v5; // rax@57
  __int64 v6; // rax@57
  __int64 v7; // rax@57
  __int64 v8; // rax@57
  signed int v9; // edx@57
  signed int v10; // eax@61
  signed int v11; // eax@64
  signed int v12; // eax@67
  signed int v13; // eax@70
  __int64 v14; // rax@73
  __int64 v15; // rax@73
  __int64 v16; // rax@73
  __int64 v17; // rax@73
  __int64 v18; // rax@73
  __int64 v19; // rax@73
  __int64 v20; // rax@73
  __int64 v21; // rax@73
  __int64 v22; // rax@73
  __int64 v23; // rax@73
  __int64 v24; // rax@73
  __int64 v25; // rax@73
  __int64 v26; // rax@73
  __int64 v27; // rax@73
  __int64 v28; // rax@73
  __int64 v29; // rax@73
  signed int v30; // ecx@73
  int v31; // er9@73
  signed int v32; // eax@77
  signed int v33; // eax@80
  signed int v34; // eax@83
  signed int v35; // eax@86
  signed int v36; // eax@89
  signed int v37; // eax@92
  signed int v38; // eax@95
  signed int v39; // eax@98
  bool v40; // r9@98
  signed int v41; // eax@102
  signed int v42; // eax@105
  signed int v43; // eax@109
  signed int v44; // eax@112
  bool v45; // r9@112
  signed int v46; // eax@116
  signed int v47; // eax@119
  signed int v48; // eax@123
  __int64 v49; // rax@126
  __int64 v50; // rax@126
  signed int v51; // ecx@126
  signed int v52; // eax@131
  __int64 v53; // rax@134
  __int64 v54; // rax@134
  signed int v55; // ecx@134
  signed int v56; // eax@138
  signed int v57; // eax@141
  signed int v58; // eax@145
  int v59; // edx@145
  signed int v60; // eax@148
  int v62; // eax@152
  __int64 v63; // rax@152
  __int64 v64; // rax@152
  __int64 v65; // rax@152
  __int64 v66; // rax@152
  __int64 v67; // rax@154
  __int64 v68; // rax@154
  __int64 v69; // rax@154
  __int64 v70; // rax@154
  __int64 v71; // rax@154
  __int64 v72; // rax@154
  __int64 v73; // rax@154
  __int64 v74; // rax@154
  __int64 v75; // rax@154
  __int64 v76; // rax@154
  __int64 v77; // rax@154
  __int64 v78; // rax@154
  __int64 v79; // rax@154
  __int64 v80; // rax@154
  __int64 v81; // rax@154
  __int64 v82; // rax@154
  __int64 v83; // rax@159
  __int64 v84; // rax@159
  __int64 v85; // rax@160
  __int64 v86; // rax@160
  int *v87; // [sp+0h] [bp-230h]@57
  __int64 v88; // [sp+8h] [bp-228h]@160
  __int64 v89; // [sp+10h] [bp-220h]@159
  __int64 *v90; // [sp+18h] [bp-218h]@154
  __int64 v91; // [sp+20h] [bp-210h]@154
  __int64 v92; // [sp+28h] [bp-208h]@154
  __int64 v93; // [sp+30h] [bp-200h]@154
  __int64 v94; // [sp+38h] [bp-1F8h]@154
  __int64 v95; // [sp+40h] [bp-1F0h]@154
  __int64 v96; // [sp+48h] [bp-1E8h]@154
  __int64 v97; // [sp+50h] [bp-1E0h]@154
  __int64 v98; // [sp+58h] [bp-1D8h]@154
  __int64 v99; // [sp+60h] [bp-1D0h]@154
  __int64 *v100; // [sp+68h] [bp-1C8h]@153
  __int64 v101; // [sp+70h] [bp-1C0h]@152
  __int64 v102; // [sp+78h] [bp-1B8h]@152
  int v103; // [sp+80h] [bp-1B0h]@152
  int v104; // [sp+84h] [bp-1ACh]@152
  __int64 *v105; // [sp+88h] [bp-1A8h]@152
  __int64 *v106; // [sp+90h] [bp-1A0h]@152
  __int64 v107; // [sp+98h] [bp-198h]@136
  __int64 v108; // [sp+A0h] [bp-190h]@128
  __int64 v109; // [sp+A8h] [bp-188h]@75
  __int64 v110; // [sp+B0h] [bp-180h]@73
  __int64 v111; // [sp+B8h] [bp-178h]@73
  __int64 v112; // [sp+C0h] [bp-170h]@73
  __int64 v113; // [sp+C8h] [bp-168h]@73
  __int64 v114; // [sp+D0h] [bp-160h]@73
  __int64 v115; // [sp+D8h] [bp-158h]@73
  __int64 v116; // [sp+E0h] [bp-150h]@73
  __int64 v117; // [sp+E8h] [bp-148h]@73
  __int64 v118; // [sp+F0h] [bp-140h]@59
  __int64 v119; // [sp+F8h] [bp-138h]@57
  int v120; // [sp+100h] [bp-130h]@57
  int v121; // [sp+104h] [bp-12Ch]@57
  int v122; // [sp+108h] [bp-128h]@52
  int v123; // [sp+10Ch] [bp-124h]@51
  int v124; // [sp+110h] [bp-120h]@50
  int v125; // [sp+114h] [bp-11Ch]@49
  int v126; // [sp+118h] [bp-118h]@48
  int v127; // [sp+11Ch] [bp-114h]@47
  int v128; // [sp+120h] [bp-110h]@46
  int v129; // [sp+124h] [bp-10Ch]@45
  int v130; // [sp+128h] [bp-108h]@44
  int v131; // [sp+12Ch] [bp-104h]@43
  int v132; // [sp+130h] [bp-100h]@42
  int v133; // [sp+134h] [bp-FCh]@41
  int v134; // [sp+138h] [bp-F8h]@40
  int v135; // [sp+13Ch] [bp-F4h]@39
  int v136; // [sp+140h] [bp-F0h]@38
  int v137; // [sp+144h] [bp-ECh]@37
  int v138; // [sp+148h] [bp-E8h]@36
  int v139; // [sp+14Ch] [bp-E4h]@35
  int v140; // [sp+150h] [bp-E0h]@34
  int v141; // [sp+154h] [bp-DCh]@33
  int v142; // [sp+158h] [bp-D8h]@32
  int v143; // [sp+15Ch] [bp-D4h]@31
  int v144; // [sp+160h] [bp-D0h]@30
  int v145; // [sp+164h] [bp-CCh]@29
  int v146; // [sp+168h] [bp-C8h]@28
  int v147; // [sp+16Ch] [bp-C4h]@27
  int v148; // [sp+170h] [bp-C0h]@26
  int v149; // [sp+174h] [bp-BCh]@25
  int v150; // [sp+178h] [bp-B8h]@24
  int v151; // [sp+17Ch] [bp-B4h]@23
  int v152; // [sp+180h] [bp-B0h]@22
  int v153; // [sp+184h] [bp-ACh]@21
  int v154; // [sp+188h] [bp-A8h]@20
  int v155; // [sp+18Ch] [bp-A4h]@19
  int v156; // [sp+190h] [bp-A0h]@18
  int v157; // [sp+194h] [bp-9Ch]@17
  int v158; // [sp+198h] [bp-98h]@16
  int v159; // [sp+19Ch] [bp-94h]@15
  int v160; // [sp+1A0h] [bp-90h]@14
  int v161; // [sp+1A4h] [bp-8Ch]@13
  int v162; // [sp+1A8h] [bp-88h]@12
  int v163; // [sp+1ACh] [bp-84h]@11
  int v164; // [sp+1B0h] [bp-80h]@10
  int v165; // [sp+1B4h] [bp-7Ch]@9
  int v166; // [sp+1B8h] [bp-78h]@8
  int v167; // [sp+1BCh] [bp-74h]@7
  int v168; // [sp+1C0h] [bp-70h]@6
  int v169; // [sp+1C4h] [bp-6Ch]@5
  int v170; // [sp+1C8h] [bp-68h]@4
  int v171; // [sp+1CCh] [bp-64h]@3
  int v172; // [sp+1D0h] [bp-60h]@2
  int v173; // [sp+1D4h] [bp-5Ch]@2
  int v174; // [sp+1D8h] [bp-58h]@1
  bool v175; // [sp+1DEh] [bp-52h]@1
  bool v176; // [sp+1DFh] [bp-51h]@1
  int *v177; // [sp+1E0h] [bp-50h]@57
  __int64 *v178; // [sp+1E8h] [bp-48h]@57
  __int64 *v179; // [sp+1F0h] [bp-40h]@57
  bool v180; // [sp+1FFh] [bp-31h]@64
  int v181; // [sp+200h] [bp-30h]@73
  unsigned int v182; // [sp+204h] [bp-2Ch]@148

  v175 = (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0;
  v176 = dword_605648 < 10;
  v174 = 16046609;
  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( 1 )
              {
                while ( 1 )
                {
                  while ( 1 )
                  {
                    while ( 1 )
                    {
                      while ( 1 )
                      {
                        while ( 1 )
                        {
                          while ( 1 )
                          {
                            while ( 1 )
                            {
                              while ( 1 )
                              {
                                while ( 1 )
                                {
                                  while ( 1 )
                                  {
                                    while ( 1 )
                                    {
                                      while ( 1 )
                                      {
                                        while ( 1 )
                                        {
                                          while ( 1 )
                                          {
                                            while ( 1 )
                                            {
                                              while ( 1 )
                                              {
                                                while ( 1 )
                                                {
                                                  while ( 1 )
                                                  {
                                                    while ( 1 )
                                                    {
                                                      v173 = v174;
                                                      v172 = v174 + 1997734765;
                                                      if ( v174 != -1997734765 )
                                                        break;
                                                      *((_DWORD *)&v87 - 4) = 0;
                                                      v106 = (__int64 *)(&v87 - 2);
                                                      v105 = (__int64 *)(&v87 - 2);
                                                      v104 = setvbuf(stdout, 0LL, 2, 0LL);
                                                      v62 = setvbuf(stdin, 0LL, 2, 0LL);
                                                      *(_DWORD *)v106 = 1;
                                                      *(_DWORD *)v105 = 0;
                                                      v103 = v62;
                                                      LODWORD(v63) = std::operator<<<std::char_traits<char>>(
                                                                       &std::cout,
                                                                       "|-------------------------------|");
                                                      LODWORD(v64) = std::ostream::operator<<(
                                                                       v63,
                                                                       &std::endl<char,std::char_traits<char>>);
                                                      v102 = v64;
                                                      LODWORD(v65) = std::operator<<<std::char_traits<char>>(
                                                                       &std::cout,
                                                                       "|AUIR AUIR AUIR AUIR AUIR AUIR A|");
                                                      LODWORD(v66) = std::ostream::operator<<(
                                                                       v65,
                                                                       &std::endl<char,std::char_traits<char>>);
                                                      v174 = -1874450811;
                                                      v101 = v66;
                                                    }
                                                    v171 = v173 + 1916674232;
                                                    if ( v173 != -1916674232 )
                                                      break;
                                                    v41 = -787818966;
                                                    if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                                                      v41 = 1209315512;
                                                    v174 = v41;
                                                  }
                                                  v170 = v173 + 1874450811;
                                                  if ( v173 != -1874450811 )
                                                    break;
                                                  v177 = (int *)(&v87 - 2);
                                                  v178 = (__int64 *)(&v87 - 2);
                                                  v179 = (__int64 *)(&v87 - 2);
                                                  *((_DWORD *)&v87 - 4) = 0;
                                                  v121 = setvbuf(stdout, 0LL, 2, 0LL);
                                                  v4 = setvbuf(stdin, 0LL, 2, 0LL);
                                                  *(_DWORD *)v178 = 1;
                                                  *(_DWORD *)v179 = 0;
                                                  v120 = v4;
                                                  LODWORD(v5) = std::operator<<<std::char_traits<char>>(
                                                                  &std::cout,
                                                                  "|-------------------------------|");
                                                  LODWORD(v6) = std::ostream::operator<<(
                                                                  v5,
                                                                  &std::endl<char,std::char_traits<char>>);
                                                  v119 = v6;
                                                  LODWORD(v7) = std::operator<<<std::char_traits<char>>(
                                                                  &std::cout,
                                                                  "|AUIR AUIR AUIR AUIR AUIR AUIR A|");
                                                  LODWORD(v8) = std::ostream::operator<<(
                                                                  v7,
                                                                  &std::endl<char,std::char_traits<char>>);
                                                  v9 = -1997734765;
                                                  if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 | (unsigned __int8)(~(dword_605648 < 10) ^ ~((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0))) & 1 )
                                                    v9 = -1337436649;
                                                  v174 = v9;
                                                  v118 = v8;
                                                }
                                                v169 = v173 + 1717401167;
                                                if ( v173 != -1717401167 )
                                                  break;
                                                v34 = 1631720898;
                                                if ( v181 < 5 )
                                                  v34 = -1624089460;
                                                v174 = v34;
                                              }
                                              v168 = v173 + 1716046051;
                                              if ( v173 != -1716046051 )
                                                break;
                                              v174 = 1742576945;
                                            }
                                            v167 = v173 + 1624089460;
                                            if ( v173 != -1624089460 )
                                              break;
                                            v46 = -704703670;
                                            if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1)
                                                                                          * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                                              v46 = -1620634609;
                                            v174 = v46;
                                          }
                                          v166 = v173 + 1622288286;
                                          if ( v173 != -1622288286 )
                                            break;
                                          LODWORD(v67) = std::operator<<<std::char_traits<char>>(
                                                           &std::cout,
                                                           "|-------------------------------|");
                                          LODWORD(v68) = std::ostream::operator<<(
                                                           v67,
                                                           &std::endl<char,std::char_traits<char>>);
                                          v99 = v68;
                                          LODWORD(v69) = std::operator<<<std::char_traits<char>>(
                                                           &std::cout,
                                                           "[1]MAKE ZEALOTS");
                                          LODWORD(v70) = std::ostream::operator<<(
                                                           v69,
                                                           &std::endl<char,std::char_traits<char>>);
                                          v98 = v70;
                                          LODWORD(v71) = std::operator<<<std::char_traits<char>>(
                                                           &std::cout,
                                                           "[2]DESTROY ZEALOTS");
                                          LODWORD(v72) = std::ostream::operator<<(
                                                           v71,
                                                           &std::endl<char,std::char_traits<char>>);
                                          v97 = v72;
                                          LODWORD(v73) = std::operator<<<std::char_traits<char>>(
                                                           &std::cout,
                                                           "[3]FIX ZEALOTS");
                                          LODWORD(v74) = std::ostream::operator<<(
                                                           v73,
                                                           &std::endl<char,std::char_traits<char>>);
                                          v96 = v74;
                                          LODWORD(v75) = std::operator<<<std::char_traits<char>>(
                                                           &std::cout,
                                                           "[4]DISPLAY SKILLS");
                                          LODWORD(v76) = std::ostream::operator<<(
                                                           v75,
                                                           &std::endl<char,std::char_traits<char>>);
                                          v95 = v76;
                                          LODWORD(v77) = std::operator<<<std::char_traits<char>>(
                                                           &std::cout,
                                                           "[5]GO HOME");
                                          LODWORD(v78) = std::ostream::operator<<(
                                                           v77,
                                                           &std::endl<char,std::char_traits<char>>);
                                          v94 = v78;
                                          LODWORD(v79) = std::operator<<<std::char_traits<char>>(
                                                           &std::cout,
                                                           "|-------------------------------|");
                                          LODWORD(v80) = std::ostream::operator<<(
                                                           v79,
                                                           &std::endl<char,std::char_traits<char>>);
                                          v93 = v80;
                                          LODWORD(v81) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
                                          v92 = v81;
                                          LODWORD(v82) = std::istream::operator>>(&std::cin, v179);
                                          v174 = 1058421619;
                                          v91 = v82;
                                          v90 = v179;
                                        }
                                        v165 = v173 + 1620634609;
                                        if ( v173 != -1620634609 )
                                          break;
                                        sub_402060();
                                        v47 = -704703670;
                                        if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1)
                                                                                      * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                                          v47 = -635610839;
                                        v174 = v47;
                                      }
                                      v164 = v173 + 1561873435;
                                      if ( v173 != -1561873435 )
                                        break;
                                      sub_400EA0();
                                      v174 = 386438049;
                                    }
                                    v163 = v173 + 1470942396;
                                    if ( v173 != -1470942396 )
                                      break;
                                    v13 = -1622288286;
                                    if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1)
                                                                                  * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                                      v13 = 1058421619;
                                    v174 = v13;
                                  }
                                  v162 = v173 + 1462815659;
                                  if ( v173 != -1462815659 )
                                    break;
                                  v11 = -1145278979;
                                  v180 = *(_DWORD *)v178 != 0;
                                  if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1)
                                                                                * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                                    v11 = 823942962;
                                  v174 = v11;
                                }
                                v161 = v173 + 1337436649;
                                if ( v173 != -1337436649 )
                                  break;
                                v174 = -1317045254;
                              }
                              v160 = v173 + 1317045254;
                              if ( v173 != -1317045254 )
                                break;
                              v10 = -1145278979;
                              if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~((((_BYTE)dword_605660
                                                                                                 - 1)
                                                                                                * (_BYTE)dword_605660 & 1) == 0)) & 1 | (unsigned __int8)(~(dword_605648 < 10) ^ ~((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0))) & 1 )
                                v10 = -1462815659;
                              v174 = v10;
                            }
                            v159 = v173 + 1246389781;
                            if ( v173 != -1246389781 )
                              break;
                            *(_DWORD *)v178 = 0;
                            LODWORD(v83) = std::operator<<<std::char_traits<char>>(
                                             &std::cout,
                                             "[*]NOOBS CAN'T PROTECT AUIR....");
                            LODWORD(v84) = std::ostream::operator<<(v83, &std::endl<char,std::char_traits<char>>);
                            v174 = 1311628157;
                            v89 = v84;
                          }
                          v158 = v173 + 1145278979;
                          if ( v173 != -1145278979 )
                            break;
                          v174 = -1462815659;
                          v100 = v178;
                        }
                        v157 = v173 + 1125410748;
                        if ( v173 != -1125410748 )
                          break;
                        LODWORD(v85) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]WRONG OPTION....");
                        LODWORD(v86) = std::ostream::operator<<(v85, &std::endl<char,std::char_traits<char>>);
                        v174 = 576367255;
                        v88 = v86;
                      }
                      v156 = v173 + 787818966;
                      if ( v173 != -787818966 )
                        break;
                      sub_401300();
                      v174 = 1209315512;
                    }
                    v155 = v173 + 704703670;
                    if ( v173 != -704703670 )
                      break;
                    sub_402060();
                    v174 = -1620634609;
                  }
                  v154 = v173 + 635610839;
                  if ( v173 != -635610839 )
                    break;
                  v174 = 1742576945;
                }
                v153 = v173 + 167280830;
                if ( v173 != -167280830 )
                  break;
                v174 = -1317045254;
              }
              v152 = v173 - 16046609;
              if ( v173 != 16046609 )
                break;
              v3 = -1997734765;
              if ( (~((unsigned __int8)~v176 | (unsigned __int8)~v175) & 1 | (unsigned __int8)(~v176 ^ ~v175)) & 1 )
                v3 = -1874450811;
              v174 = v3;
            }
            v151 = v173 - 165826593;
            if ( v173 != 165826593 )
              break;
            sub_401680();
            v174 = 698358076;
          }
          v150 = v173 - 170875644;
          if ( v173 != 170875644 )
            break;
          v57 = 1828961499;
          if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~((((_BYTE)dword_605660 - 1)
                                                                            * (_BYTE)dword_605660 & 1) == 0)) & 1 | (unsigned __int8)(~(dword_605648 < 10) ^ ~((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0))) & 1 )
            v57 = -167280830;
          v174 = v57;
        }
        v149 = v173 - 187950896;
        if ( v173 != 187950896 )
          break;
        v32 = 1830401682;
        if ( v181 < 3 )
          v32 = 960443792;
        v174 = v32;
      }
      v148 = v173 - 386438049;
      if ( v173 != 386438049 )
        break;
      sub_400EA0();
      v39 = -1561873435;
      v40 = (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0;
      if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~v40) & 1 | (unsigned __int8)((dword_605648 < 10) ^ v40)) & 1 )
        v39 = -1716046051;
      v174 = v39;
    }
    v147 = v173 - 403638534;
    if ( v173 == 403638534 )
      break;
    v146 = v173 - 431652692;
    if ( v173 == 431652692 )
    {
      v174 = 1692233395;
    }
    else
    {
      v145 = v173 - 576367255;
      if ( v173 == 576367255 )
      {
        LODWORD(v53) = std::operator<<<std::char_traits<char>>(&std::cout, "[*]WRONG OPTION....");
        LODWORD(v54) = std::ostream::operator<<(v53, &std::endl<char,std::char_traits<char>>);
        v55 = -1125410748;
        if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
          v55 = 1805622087;
        v174 = v55;
        v107 = v54;
      }
      else
      {
        v144 = v173 - 639697365;
        if ( v173 == 639697365 )
        {
          v60 = 1806825442;
          v182 = *v177;
          if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
            v60 = 403638534;
          v174 = v60;
        }
        else
        {
          v143 = v173 - 698358076;
          if ( v173 == 698358076 )
          {
            sub_401680();
            v44 = 165826593;
            v45 = (((_BYTE)dword_605660 - 82 + 81) * (_BYTE)dword_605660 & 1) == 0;
            if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~v45) & 1 | (unsigned __int8)((dword_605648 < 10) ^ v45)) & 1 )
              v44 = 1874468343;
            v174 = v44;
          }
          else
          {
            v142 = v173 - 823942962;
            if ( v173 == 823942962 )
            {
              v12 = 1648947149;
              if ( v180 )
                v12 = -1470942396;
              v174 = v12;
            }
            else
            {
              v141 = v173 - 960443792;
              if ( v173 == 960443792 )
              {
                v36 = -1916674232;
                if ( v181 < 2 )
                  v36 = 1946562061;
                v174 = v36;
              }
              else
              {
                v140 = v173 - 1007567104;
                if ( v173 == 1007567104 )
                {
                  v38 = -1561873435;
                  if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~((((_BYTE)dword_605660 - 1)
                                                                                    * (_BYTE)dword_605660 & 1) == 0)) & 1 | (unsigned __int8)(~(dword_605648 < 10) ^ ~((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0))) & 1 )
                    v38 = 386438049;
                  v174 = v38;
                }
                else
                {
                  v139 = v173 - 1017248874;
                  if ( v173 == 1017248874 )
                  {
                    v174 = 1742576945;
                  }
                  else
                  {
                    v138 = v173 - 1058421619;
                    if ( v173 == 1058421619 )
                    {
                      LODWORD(v14) = std::operator<<<std::char_traits<char>>(
                                       &std::cout,
                                       "|-------------------------------|");
                      LODWORD(v15) = std::ostream::operator<<(v14, &std::endl<char,std::char_traits<char>>);
                      v117 = v15;
                      LODWORD(v16) = std::operator<<<std::char_traits<char>>(&std::cout, "[1]MAKE ZEALOTS");
                      LODWORD(v17) = std::ostream::operator<<(v16, &std::endl<char,std::char_traits<char>>);
                      v116 = v17;
                      LODWORD(v18) = std::operator<<<std::char_traits<char>>(&std::cout, "[2]DESTROY ZEALOTS");
                      LODWORD(v19) = std::ostream::operator<<(v18, &std::endl<char,std::char_traits<char>>);
                      v115 = v19;
                      LODWORD(v20) = std::operator<<<std::char_traits<char>>(&std::cout, "[3]FIX ZEALOTS");
                      LODWORD(v21) = std::ostream::operator<<(v20, &std::endl<char,std::char_traits<char>>);
                      v114 = v21;
                      LODWORD(v22) = std::operator<<<std::char_traits<char>>(&std::cout, "[4]DISPLAY SKILLS");
                      LODWORD(v23) = std::ostream::operator<<(v22, &std::endl<char,std::char_traits<char>>);
                      v113 = v23;
                      LODWORD(v24) = std::operator<<<std::char_traits<char>>(&std::cout, "[5]GO HOME");
                      LODWORD(v25) = std::ostream::operator<<(v24, &std::endl<char,std::char_traits<char>>);
                      v112 = v25;
                      LODWORD(v26) = std::operator<<<std::char_traits<char>>(
                                       &std::cout,
                                       "|-------------------------------|");
                      LODWORD(v27) = std::ostream::operator<<(v26, &std::endl<char,std::char_traits<char>>);
                      v111 = v27;
                      LODWORD(v28) = std::operator<<<std::char_traits<char>>(&std::cout, ">>");
                      v110 = v28;
                      LODWORD(v29) = std::istream::operator>>(&std::cin, v179);
                      v30 = -1622288286;
                      v181 = *(_DWORD *)v179;
                      v31 = ((_BYTE)dword_605660 - 101 + 100) * (_BYTE)dword_605660 & 1;
                      if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~(v31 == 0)) & 1 | (unsigned __int8)(~(dword_605648 < 10) ^ ~(v31 == 0))) & 1 )
                        v30 = 1496294532;
                      v174 = v30;
                      v109 = v29;
                    }
                    else
                    {
                      v137 = v173 - 1103101655;
                      if ( v173 == 1103101655 )
                      {
                        v43 = 165826593;
                        if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                          v43 = 698358076;
                        v174 = v43;
                      }
                      else
                      {
                        v136 = v173 - 1209315512;
                        if ( v173 == 1209315512 )
                        {
                          sub_401300();
                          v42 = -787818966;
                          if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~((((_BYTE)dword_605660 - 1)
                                                                                            * (_BYTE)dword_605660 & 1) == 0)) & 1 | (unsigned __int8)(~(dword_605648 < 10) ^ ~((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0))) & 1 )
                            v42 = 1017248874;
                          v174 = v42;
                        }
                        else
                        {
                          v135 = v173 - 1311628157;
                          if ( v173 == 1311628157 )
                          {
                            *(_DWORD *)v178 = 0;
                            LODWORD(v49) = std::operator<<<std::char_traits<char>>(
                                             &std::cout,
                                             "[*]NOOBS CAN'T PROTECT AUIR....");
                            LODWORD(v50) = std::ostream::operator<<(v49, &std::endl<char,std::char_traits<char>>);
                            v51 = -1246389781;
                            if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1)
                                                                          * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                              v51 = 1885086154;
                            v174 = v51;
                            v108 = v50;
                          }
                          else
                          {
                            v134 = v173 - 1442982074;
                            if ( v173 == 1442982074 )
                            {
                              v48 = -1246389781;
                              if ( (~((unsigned __int8)~(dword_605648 < 10) | (unsigned __int8)~((((_BYTE)dword_605660
                                                                                                 - 1)
                                                                                                * (_BYTE)dword_605660 & 1) == 0)) & 1 | (unsigned __int8)(~(dword_605648 < 10) ^ ~((((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0))) & 1 )
                                v48 = 1311628157;
                              v174 = v48;
                            }
                            else
                            {
                              v133 = v173 - 1496294532;
                              if ( v173 == 1496294532 )
                              {
                                v174 = 187950896;
                              }
                              else
                              {
                                v132 = v173 - 1631720898;
                                if ( v173 == 1631720898 )
                                {
                                  v35 = 431652692;
                                  if ( v181 == 5 )
                                    v35 = 1442982074;
                                  v174 = v35;
                                }
                                else
                                {
                                  v131 = v173 - 1648947149;
                                  if ( v173 == 1648947149 )
                                  {
                                    v58 = 1806825442;
                                    v59 = ((_BYTE)dword_605660 - 61 + 60) * (_BYTE)dword_605660 & 1;
                                    if ( ((unsigned __int8)((dword_605648 < 10) ^ (v59 == 0)) | (dword_605648 < 10
                                                                                              && v59 == 0)) & 1 )
                                      v58 = 639697365;
                                    v174 = v58;
                                  }
                                  else
                                  {
                                    v130 = v173 - 1692233395;
                                    if ( v173 == 1692233395 )
                                    {
                                      v52 = -1125410748;
                                      if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1)
                                                                                    * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                                        v52 = 576367255;
                                      v174 = v52;
                                    }
                                    else
                                    {
                                      v129 = v173 - 1742576945;
                                      if ( v173 == 1742576945 )
                                      {
                                        v56 = 1828961499;
                                        if ( ((unsigned __int8)((dword_605648 < 10) ^ ((((_BYTE)dword_605660 - 1)
                                                                                      * (_BYTE)dword_605660 & 1) == 0)) | (dword_605648 < 10 && (((_BYTE)dword_605660 - 1) * (_BYTE)dword_605660 & 1) == 0)) & 1 )
                                          v56 = 170875644;
                                        v174 = v56;
                                      }
                                      else
                                      {
                                        v128 = v173 - 1805622087;
                                        if ( v173 == 1805622087 )
                                        {
                                          v174 = 1742576945;
                                        }
                                        else
                                        {
                                          v127 = v173 - 1806825442;
                                          if ( v173 == 1806825442 )
                                          {
                                            v174 = 639697365;
                                            v87 = v177;
                                          }
                                          else
                                          {
                                            v126 = v173 - 1828961499;
                                            if ( v173 == 1828961499 )
                                            {
                                              v174 = 170875644;
                                            }
                                            else
                                            {
                                              v125 = v173 - 1830401682;
                                              if ( v173 == 1830401682 )
                                              {
                                                v33 = -1717401167;
                                                if ( v181 < 4 )
                                                  v33 = 1103101655;
                                                v174 = v33;
                                              }
                                              else
                                              {
                                                v124 = v173 - 1874468343;
                                                if ( v173 == 1874468343 )
                                                {
                                                  v174 = 1742576945;
                                                }
                                                else
                                                {
                                                  v123 = v173 - 1885086154;
                                                  if ( v173 == 1885086154 )
                                                  {
                                                    v174 = 1742576945;
                                                  }
                                                  else
                                                  {
                                                    v122 = v173 - 1946562061;
                                                    if ( v173 == 1946562061 )
                                                    {
                                                      v37 = 431652692;
                                                      if ( v181 == 1 )
                                                        v37 = 1007567104;
                                                      v174 = v37;
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  return v182;
}
// 400990: using guessed type int __fastcall std::operator<<<std::char_traits<char>>(_QWORD, _QWORD);
// 4009B0: using guessed type int __fastcall std::istream::operator>>(_QWORD, _QWORD);
// 4009C0: using guessed type int __fastcall std::ostream::operator<<(_QWORD, _QWORD);
// 605648: using guessed type int dword_605648;
// 605660: using guessed type int dword_605660;

//----- (0000000000403AC0) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13@1
  signed __int64 v4; // rbp@1
  __int64 v5; // rbx@2

  v3 = a3;
  v4 = &off_604DE8 - off_604DD8;
  init_proc();
  if ( v4 )
  {
    v5 = 0LL;
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))off_604DD8[v5++])(a1, a2, v3);
    while ( v5 != v4 );
  }
}
// 604DD8: using guessed type __int64 (__fastcall *off_604DD8[3])();
// 604DE8: using guessed type __int64 (__fastcall *off_604DE8)();

//----- (0000000000403B34) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 14 function(s)"
