/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// void free(void *ptr);
// int puts(const char *s);
// ssize_t write(int fd, const void *buf, size_t n);
// char *strchr(const char *s, int c);
// int printf(const char *format, ...);
// int snprintf(char *s, size_t maxlen, const char *format, ...);
// void *memset(void *s, int c, size_t n);
// int close(int fd);
// ssize_t read(int fd, void *buf, size_t nbytes);
// int __gmon_start__(void); weak
// void *memcpy(void *dest, const void *src, size_t n);
// void *malloc(size_t size);
// int setvbuf(FILE *stream, char *buf, int modes, size_t n);
// int open(const char *file, int oflag, ...);
// int __fastcall __isoc99_scanf(_QWORD, _QWORD); weak
// void __noreturn exit(int status);
signed int sub_400950();
int sub_400980();
signed int sub_4009C0();
int sub_4009E0();
int __fastcall main(__int64 a1, char **a2, char **a3);
void __fastcall sub_400B3A(__int64 a1, int a2);
void *sub_400F2D();
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *off_601E10[2])() = { &sub_4009E0, &sub_4009C0 }; // weak
__int64 (__fastcall *off_601E18)() = &sub_4009C0; // weak
FILE *stdout; // idb
char byte_6020C8; // weak
__int64 qword_6020E0; // weak
char byte_602100[512]; // idb
int dword_602300; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (00000000004007C8) ----------------------------------------------------
int init_proc()
{
  void *v0; // rax@1

  v0 = &_gmon_start__;
  if ( &_gmon_start__ )
    LODWORD(v0) = __gmon_start__();
  return (unsigned __int64)v0;
}
// 4008B0: using guessed type int __gmon_start__(void);

//----- (0000000000400920) ----------------------------------------------------
#error "400926: positive sp value has been found (funcsize=3)"

//----- (0000000000400950) ----------------------------------------------------
signed int sub_400950()
{
  return 7;
}

//----- (0000000000400980) ----------------------------------------------------
int sub_400980()
{
  return 0;
}

//----- (00000000004009C0) ----------------------------------------------------
signed int sub_4009C0()
{
  signed int result; // eax@2

  if ( !byte_6020C8 )
  {
    result = sub_400950();
    byte_6020C8 = 1;
  }
  return result;
}
// 6020C8: using guessed type char byte_6020C8;

//----- (00000000004009E0) ----------------------------------------------------
int sub_4009E0()
{
  return sub_400980();
}
// 4009E0: could not find valid save-restore pair for rbp

//----- (0000000000400A0D) ----------------------------------------------------
int __fastcall main(__int64 a1, char **a2, char **a3)
{
  char v4; // [sp+Bh] [bp-5h]@4
  int fd; // [sp+Ch] [bp-4h]@1

  setvbuf(stdout, 0LL, 2, 0LL);
  memset(byte_602100, 0, 0x200uLL);
  memcpy(byte_602100, "Default Highscore ", 0x14uLL);
  dword_602300 = 64;
  fd = open("/dev/urandom", 0);
  if ( fd == -1 )
    exit(1);
  qword_6020E0 = (__int64)sub_400F2D();
  printf("Welcome %s\n", *(_QWORD *)(qword_6020E0 + 8));
  do
  {
    sub_400B3A(qword_6020E0, fd);
    printf("%s ", byte_602100);
    printf("score: %d\n", (unsigned int)dword_602300);
    printf("Continue? ");
    __isoc99_scanf(" %c", &v4);
  }
  while ( v4 != 110 );
  return close(fd);
}
// 400900: using guessed type int __fastcall __isoc99_scanf(_QWORD, _QWORD);
// 6020E0: using guessed type __int64 qword_6020E0;
// 602300: using guessed type int dword_602300;

//----- (0000000000400B3A) ----------------------------------------------------
void __fastcall sub_400B3A(__int64 a1, int a2)
{
  char v2; // [sp+1Ah] [bp-46h]@5
  char v3; // [sp+1Bh] [bp-45h]@29
  int v4; // [sp+1Ch] [bp-44h]@5
  int v5; // [sp+20h] [bp-40h]@5
  int v6; // [sp+24h] [bp-3Ch]@1
  int v7; // [sp+28h] [bp-38h]@17
  int v8; // [sp+2Ch] [bp-34h]@30
  unsigned __int64 i; // [sp+30h] [bp-30h]@2
  unsigned __int64 j; // [sp+38h] [bp-28h]@6
  unsigned __int64 k; // [sp+40h] [bp-20h]@17
  void *buf; // [sp+48h] [bp-18h]@1
  void *s; // [sp+50h] [bp-10h]@30
  char *v14; // [sp+58h] [bp-8h]@30

  v6 = *(_DWORD *)(a1 + 4);
  buf = malloc(v6);
  if ( buf )
  {
    read(a2, buf, v6);
    for ( i = 0LL; v6 - 1 > i; ++i )
    {
      *((_BYTE *)buf + i) ^= *(_BYTE *)(*(_QWORD *)(a1 + 8) + i);
      *((_BYTE *)buf + i) = *((_BYTE *)buf + i) % 0x1Au + 97;
    }
    v4 = 3;
    v5 = 0;
    v2 = 95;
    while ( v4 > 0 )
    {
      for ( j = 0LL; v6 - 1 > j; ++j )
      {
        if ( *(_BYTE *)(a1 + *((_BYTE *)buf + j) - 97 + 16) )
          write(1, (char *)buf + j, 1uLL);
        else
          write(1, "_", 1uLL);
      }
      write(1, "\n", 1uLL);
      __isoc99_scanf(" %c", &v2);
      if ( v2 > 96 && v2 <= 122 )
      {
        if ( *(_BYTE *)(a1 + v2 - 97 + 16) )
        {
          puts("nope");
          --v4;
        }
        else
        {
          v7 = v5;
          for ( k = 0LL; v6 - 1 > k; ++k )
          {
            if ( *((_BYTE *)buf + k) == v2 )
            {
              *(_BYTE *)(a1 + v2 - 97 + 16) = 1;
              ++v5;
            }
          }
          if ( v7 == v5 )
            --v4;
          if ( v6 - 1 <= v5 )
          {
            *(_DWORD *)a1 = (signed int)floor((double)(v6 - 1) * 0.25 * 32.0 + (double)*(signed int *)a1);
            goto LABEL_28;
          }
        }
      }
      else
      {
        puts("nope");
        --v4;
      }
    }
    *(_DWORD *)a1 = (signed int)floor((double)(v6 - 1) * 0.25 * (double)v5 + (double)*(signed int *)a1);
LABEL_28:
    if ( *(_DWORD *)a1 > dword_602300 )
    {
      puts("High score! change name?");
      __isoc99_scanf(" %c", &v3);
      if ( v3 == 121 )
      {
        s = malloc(0xF8uLL);
        memset(s, 0, 0xF8uLL);
        v8 = read(0, s, 0xF8uLL);
        *(_DWORD *)(a1 + 4) = v8;
        v14 = strchr((const char *)s, 10);
        if ( v14 )
          *v14 = 0;
        memcpy(*(void **)(a1 + 8), s, v8);
        free(s);
      }
      snprintf(byte_602100, 0x200uLL, "Highest player: %s", *(_QWORD *)(a1 + 8));
      dword_602300 = *(_DWORD *)a1;
    }
    memset((void *)(a1 + 16), 0, 0x1AuLL);
    free(buf);
  }
}
// 400900: using guessed type int __fastcall __isoc99_scanf(_QWORD, _QWORD);
// 602300: using guessed type int dword_602300;

//----- (0000000000400F2D) ----------------------------------------------------
void *sub_400F2D()
{
  void *v0; // ST10_8@3
  void *v1; // ST18_8@3
  void *result; // rax@3
  __int64 v3; // rbx@3
  int v4; // [sp+Ch] [bp-124h]@1
  char *v5; // [sp+10h] [bp-120h]@1
  char s; // [sp+20h] [bp-110h]@1
  __int64 v7; // [sp+118h] [bp-18h]@1

  v7 = *MK_FP(__FS__, 40LL);
  write(1, "What's your name?\n", 0x12uLL);
  memset(&s, 0, 0xF8uLL);
  v4 = read(0, &s, 0xF7uLL);
  v5 = strchr(&s, 10);
  if ( v5 )
    *v5 = 0;
  v0 = malloc(v4);
  v1 = malloc(0x80uLL);
  memset(v1, 0, 0x80uLL);
  *((_QWORD *)v1 + 1) = v0;
  *((_DWORD *)v1 + 1) = v4;
  memcpy(*((void **)v1 + 1), &s, v4);
  result = v1;
  v3 = *MK_FP(__FS__, 40LL) ^ v7;
  return result;
}

//----- (0000000000401080) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r13@1
  __int64 v4; // rbx@1
  signed __int64 v5; // rbp@1

  v3 = a3;
  v4 = 0LL;
  v5 = &off_601E18 - off_601E10;
  init_proc();
  if ( v5 )
  {
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))off_601E10[v4++])(a1, a2, v3);
    while ( v4 != v5 );
  }
}
// 601E10: using guessed type __int64 (__fastcall *off_601E10[2])();
// 601E18: using guessed type __int64 (__fastcall *off_601E18)();

//----- (00000000004010F4) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 11 function(s)"
